name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Set this to the branch you want to trigger the build

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # GitHub Actions runner
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4  # Checks out your repository under $GITHUB_WORKSPACE, so your workflow can access it

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Set your DockerHub username in GitHub secrets
          password: ${{ secrets.DOCKER_TOKEN }}  # Set your DockerHub token in GitHub secrets

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: andrew840513/cic-tracker:once  # Adjust tag as needed
          platforms: linux/amd64,linux/arm64
